### PR TITLE
STOR-1598: Rebase to v1.32.0 for OCP 4.17

### PR DESCRIPTION
**Pull request by jsafrane**
https://github.com/openshift/aws-ebs-csi-driver/pull/270 rebases to 1.31.0, this one rebases to 1.32.0. I will see what CI says.

Notable changes:

* Migrate to AWS SDKv2 ( i.e. regressions could happen & CI should catch them. Please check with STS!)
* Add c6id and r6id adjusted limits to volume_limits.go

Full upstream changelogs: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG.md

Diff to upstream v1.32.0:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/compare/v1.32.0...jsafrane:rebase-v1.32.0 

@openshift/storage

### CODE REVIEW

**Comment by Phaow** [comment]
Hi @jsafrane , pre merge test with `4.17.0-0.test-2024-07-16-063504-ci-ln-zj359k2-latest`, the `c6id` instance type csinode allocatable volumes count issue fixed by https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2065 in the `v1.32.0`. [Regression tests](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/ginkgo-test/257622/console) on aws-ipi-proxy-sts all looks good. Unfortunately even if use the latest driver some instance types max allocatable volumes count still incorrect(also for 4.16). I opened https://issues.redhat.com/browse/OCPBUGS-37088 to track.

```console
sh-5.1$ ./bin/aws-ebs-csi-driver --version
{
  "driverVersion": "v1.32.0",
  "gitCommit": "d079c81efb4f782bee9dd106bf5e206a0364fa61",
  "buildDate": "2024-07-16T06:32:07+00:00",
  "goVersion": "go1.22.4 (Red Hat 1.22.4-2.el9) X:strictfipsruntime",
  "compiler": "gc",
  "platform": "linux/amd64"
}

# Regression test result
64 pass, 48 skip (30m58s)
```

**Comment by Phaow** [comment]
BTW, I saw https://github.com/openshift/release/pull/54323 already merged, not sure why the `verify-deps` still failed, the rebase all looks good except this unit test. Will label `qe-approved` when the ut test passed.

**Comment by jsafrane** [comment]
> not sure why the verify-deps still failed

I know! Files in vendor/ are incorrect, some script (`make update`?) removed license headers from them. Fixing it shortly...

**Comment by jsafrane** [comment]
I updated `vendor` to be correct (i.e. have content from `go mod vendor`), now `make verify` will fail because files in `vendor/` have a wrong header. I am fixing the check in https://github.com/openshift/release/pull/54403

**Pull request merged**
