### PR TITLE
Bug 1955474: Rebase v1.0.0

### PR DESCRIPTION
**Pull request by bertinatto**
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/compare/v1.0.0...bertinatto:rebase-v1.0

CC @openshift/storage 

/hold
Just checking CI for now.

### CODE REVIEW

**Comment by jsafrane** [comment]
/test e2e-aws-csi
2nd run just to be sure

**Comment by bertinatto** [comment]
/hold cancel
PR is ready to be merged, assuming CI is green.

**Comment by jsafrane** [comment]
/lgtm
This will be re-tested number of times because of our faulty snapshot tests. Please watch for any other failed tests.

**Pull request merged**
