### PR TITLE
STOR-1400: Rebase to v1.22.0 for OCP 4.15

### PR DESCRIPTION
**Pull request by mpatlasov**
Diff to upstream v1.22.0:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/compare/v1.22.0...mpatlasov:rebase-v1.22.0

Notable changes since v1.18.0 (OCP 4.14):

 * Enable leader election in csi-resizer sidecar ([#1606](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1606), [@rdpsin](https://github.com/rdpsin))
 * Namespace-scoped leases permissions ([#1614](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1614), [@torredil](https://github.com/torredil))
 * Add additionalArgs parameter for sidecars ([#1627](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1627), [@ConnorJC3](https://github.com/ConnorJC3))
 * Fix context handling in WaitForVolumeAttachment & add in-flight checks to attachment/detachment operations ([#1621](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1621), [@torredil](https://github.com/torredil))
 * Extend resource list in Kustomization file ([#1634](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1634), [@torredil](https://github.com/torredil))
 * Add support for annotation-based volume modification via volume-modifier-for-k8s sidecar ([#1600](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1600), [@rdpsin](https://github.com/rdpsin))
 * Add startup taint removal feature ([#1588](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1588), [@ConnorJC3](https://github.com/ConnorJC3) and [@gtxu](https://github.com/gtxu))

Full changelog: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG.md

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
We need to discuss is we're going to support these two features and how. They may require change in our operators.

> * Add support for annotation-based volume modification via volume-modifier-for-k8s sidecar (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1600, [@rdpsin](https://github.com/rdpsin))
> * Add startup taint removal feature (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1588, [@ConnorJC3](https://github.com/ConnorJC3) and [@gtxu](https://github.com/gtxu))

I added a topic to the next design meeting. @mpatlasov can you please check what they do?

**Comment by mpatlasov** [comment]
/hold
(bump to 1.22 would be too dangerous at this time of 4.14 development)

**Comment by jsafrane** [comment]
/close
Replaced by https://github.com/openshift/aws-ebs-csi-driver/pull/244
(sorry, we had to rebase and then I picked v1.25.0)

**Pull request closed without merging**
