### PR TITLE
Rebase v1.5.1

### PR DESCRIPTION
**Pull request by bertinatto**
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/compare/v1.5.1...bertinatto:rebase-v1.5.1

CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
/hold
Until the team agrees whether this is a good idea.

**Comment by dobsonj** [comment]
/lgtm
I think we want this in master anyway, but leaving the hold until we discuss with the rest of the team.

**Comment by jsafrane** [comment]
/hold cancel

+1, we want it in master anyway.

**Pull request merged**
