### PR TITLE
STOR-2016: Rebase to upstream v1.34.0 for OCP 4.18

### PR DESCRIPTION
**Pull request by dfajmon**
Issue link:
https://issues.redhat.com/browse/STOR-2016

Diff to upstream v1.32.0:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/compare/v1.32.0...dfajmon:rebase-v1.34.0

Changes between v1.32.0 (OCP 4.17) and v1.34.0 (OCP 4.18):
> [!IMPORTANT]
> The AZ topology key `CreateVolume` returns has changed from `topology.ebs.csi.aws.com/zone` to `topology.kubernetes.io/zone`. Volumes created on `v1.33.0` or any future version will be incompatible with versions before `v1.28.0`. No other customer-facing impact is expected unless you directly depend on the topology label. For more information and the reasoning behind this change, see [issue #729](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/729#issuecomment-1942026577).

- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2103
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2086
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2082
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2081

Full changelogs:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG.md

@openshift/storage

### CODE REVIEW

**Comment by dfajmon** [comment]
/hold
need to figure out what to do with `ci/prow/e2e-aws-csi-extended` as it works with `topology.ebs.csi.aws.com/zone` which is changing to `topology.kubernetes.io/zone`

**Comment by dfajmon** [comment]
/unhold
https://github.com/openshift/openshift-tests-private/pull/19938 fixes the problem with aws-csi-extended CSI but this needs to be merged first

**Comment by Phaow** [comment]
Pre merge test with `4.18.0-0.test-2024-09-25-010000-ci-ln-2ilsfpk-latest (build 4.18,openshift/aws-ebs-csi-driver#276)`,
all regression test [passed](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/ginkgo-test/270165/console).

```console
66 pass, 55 skip (31m34s)
```

> - Ensure ModifyVolume returns InvalidArgument error code if VAC contains invalid parameter kubernetes-sigs/aws-ebs-csi-driver#2103
> - Modifying Tags On Existing Volume kubernetes-sigs/aws-ebs-csi-driver#2082

The 2 new notable changes needs https://issues.redhat.com/browse/STOR-2078 finish to test. I tried with `oc patch featuregate cluster -p '{"spec":{"featureSet":"CustomNoUpgrade","customNoUpgrade":{"enabled":["VolumeAttributesClass"]}}}' --type=merge`, it seems  does not work. Will retest when https://issues.redhat.com/browse/STOR-2078 ready to test.

**Pull request merged**
