### PR TITLE
Bug 1870647: Rebase v6

### PR DESCRIPTION
**Pull request by huffmanca**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Rebases to the upstream v0.6.0 tag.

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/compare/v0.6.0...huffmanca:rebase-v6

### CODE REVIEW

**Comment by jsafrane** [comment]
@huffmanca I am afraid the verify error is genuine, something's wrong with golint.

**Comment by huffmanca** [comment]
@jsafrane 

> @huffmanca I am afraid the verify error is genuine, something's wrong with golint.

I modified the golangci to use `modules-download-mode: vendor` instead of `modules-download-mode: reaodnly`, and this appears to resolve the verify issues.

**Pull request merged**
