### PR TITLE
[release-4.14] OCPBUGS-33078: UPSTREAM: 1919: Add reserved-volume-attachments

### PR DESCRIPTION
**Pull request by jsafrane**
Pick both commits from https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1919 to OCP.

Introduce --reserved-volume-attachments cmd line option that disables loading list of volume attachments from instance metadata.

Instance metadata has volume attachments that were present on instance boot, which may be different than the current nr. of attachments. In addition, it may include CSI volumes that were not drained before reboot, and thus the value may be completely wrong.

--reserved-volume-attachments simply reserves given nr. of attachments for any system disks. Typically it should be 1 for the root volume.

cc @openshift/storage

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
/lgtm
/label backport-risk-assessed

**Comment by Phaow** [comment]
/label cherry-pick-approved
/label qe-approved

Pre verify passed on `4.14.0-0.test-2024-04-30-012715-ci-ln-8rl5pfb-latest` (build 4.14,openshift/aws-ebs-csi-driver#264,openshift/aws-ebs-csi-driver-operator#306)

Firstly I checked the `--reserved-volume-attachments=1` arg already added to csi-node ds in the fix build.

 ```console
$ oc -n openshift-cluster-csi-drivers get ds/aws-ebs-csi-driver-node -oyaml| grep 'reserved'
        - --reserved-volume-attachments=1
```
The presubmit CI all looks good regression test passed. In addition, I tested with fresh installed pre merge build cluster with m5.8xlarge instance type(csinode allocatable volumes count: "26"), create statefulset with pvc 20 replicas use nodeAffinity to make the pod schedule to specified node and reboot the node several times, then create statefulset with pvc 6 replicas use nodeAffinity to make the pod schedule to specified node, the sts all replicas become ready.

**Pull request merged**
