### PR TITLE
STOR-1598: Rebase to upstream 1.31.0 for 4.17

### PR DESCRIPTION
**Pull request by jsafrane**
Notable changes:

* Migrate to AWS SDKv2 ( i.e. regressions could happen & CI should catch them. Please check with STS!)
* Add c6id and r6id adjusted limits to volume_limits.go

Full upstream changelogs: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG.md

Diff to upstream v1.31.0:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/compare/v1.31.0...jsafrane:rebase-v1.31.0 

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
We don't have go 1.22.3 in CI yet :-(
https://issues.redhat.com/browse/ART-9927

**Comment by Phaow** [comment]
Hi @jsafrane , when I pre merge test with this PR(`4.17.0-0.test-2024-07-09-011823-ci-ln-br5gh4b-latest`), I found that seems the driver version missed update to `1.31.0` maybe in some makefile variables -> https://github.com/jsafrane/aws-ebs-csi-driver/blob/rebase-1.31.0/Makefile#L36 . BTW, upstream released `v1.32.0` two weeks ago, seems minor bug fix, do we plan to use the `v1.32.0` for 4.17. Checking the STS configuration in progress.

In addition, it seems the `c6id.2xlarge` instance type csinode allocatable volumes count still incorrect, from the offical doc it seems the fix is correct but in actual tests it failed when attach the 26th volume(csinode allocatable volumes count is 26). Not sure the aws backend changed something, anyway I open 1 aws ticket to double confirm the instance type actual support allocatable volumes count.
https://support.console.aws.amazon.com/support/home?region=us-east-2#/case/?displayId=172059617200275&language=en

```console
$ oc rsh -c csi-driver aws-ebs-csi-driver-controller-56646d49d7-7md9h
sh-5.1$  /usr/bin/aws-ebs-csi-driver --version
{
  "driverVersion": "v1.30.0",
  "gitCommit": "f25dc874cf723f849e81df21902c1ce89a975d5f",
  "buildDate": "2024-07-09T01:14:57+00:00",
  "goVersion": "go1.22.4 (Red Hat 1.22.4-2.el9) X:strictfipsruntime",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**Comment by jsafrane** [comment]
> BTW, upstream released `v1.32.0` two weeks ago, seems minor bug fix, do we plan to use the `v1.32.0` for 4.17. 

I opened https://github.com/openshift/aws-ebs-csi-driver/pull/272 with 1.32.0, I hope it fixes verification bugs that I see here.

I updated the version string to v1.32.0, they seem to always be off by one.

**Comment by jsafrane** [comment]
/close 
in favor of https://github.com/openshift/aws-ebs-csi-driver/pull/272

**Pull request closed without merging**
