### PR TITLE
UPSTREAM: 912: Bug 1962415: remove WellKnownTopologyKey from PV Topology

### PR DESCRIPTION
**Pull request by Elbehery**
**Is this a bug fix or adding new feature?**
bug fix
**What is this PR about? / Why do we need it?**
fixes https://github.com/kubernetes/kubernetes/issues/102248
**What testing is done?** 
modified testing and verified

### CODE REVIEW

**Comment by gnufied** [comment]
/hold

Can we instead rebase against 1.1 release so as we get more than one bug fix?

**Comment by Elbehery** [comment]
this fix has been merged in https://github.com/openshift/aws-ebs-csi-driver/pull/187

Closing

**Pull request closed without merging**
