### PR TITLE
STOR-860: Rebase to v1.11.4 for OCP 4.12

### PR DESCRIPTION
**Pull request by jsafrane**
Diff to upstream v1.11.4:
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/compare/v1.11.4...jsafrane:rebase-v1.11.2

Notable changes since v1.5.1 @ 4.11:

* Upstream dropped `vendor/` directory, added it back + updated Makefile to build with `-mod=vendor`  for offline OCP builds.
* Use mount utils to check if volume needs resizing
* Adding tagging support through StorageClass.parameters

Full changelog: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG.md

@openshift/storage

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
/lgtm
/retest

**Comment by jsafrane** [comment]
I'm fixing CSI migration in https://github.com/openshift/release/pull/32069 and I'd like this PR to pass
/hold

**Comment by jsafrane** [comment]
/retest
storage tests passed, but there were some hiccups when talking to the API server

**Comment by jsafrane** [comment]
Updated to 1.11.4, because 1.11.3 claims it fixes CVE: https://github.com/advisories/GHSA-cg3q-j54f-5p7p, https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1384

**Comment by jsafrane** [comment]
And bumped go to 1.19, required by the driver now.

**Comment by jsafrane** [comment]
/retest
go 1.19 should be used by CI now...

**Comment by jsafrane** [comment]
/label docs-approved
/label px-approved

We don't document / announce CSI driver version bumps to customers.

**Comment by jsafrane** [comment]
I finally convinced CI to run `make verify` without Kubernetes env. variables.

**Comment by Phaow** [comment]
Pre verify pass with `* Clusterversion: 4.12.0-0.ci.test-2022-09-27-002049-ci-ln-2iv4tmk-latest * Platform: AWS * NetWorking: OVNKubernetes *`
 All the **[regression automation test](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/ginkgo-test/112373/console)** passed and the new feature about `Tags` usage manual test passed.
```
error: 1 fail, 58 pass, 58 skip (1h3m17s)
```
The 1 failed is caused by in `sts` cluster the credential don't has the reboot instance right. I'll fix the code later.

It seems only a bit strange issue about check the driver version, I'm not sure what causes the driverVersion not as expected by check cmd. It should be `1.11.3` from the `Makefile` https://github.com/openshift/aws-ebs-csi-driver/pull/206/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R28 .
```
$ oc -n openshift-cluster-csi-drivers exec -c csi-driver deploy/aws-ebs-csi-driver-controller -- /bin/aws-ebs-csi-driver -version | jq .
{
  "driverVersion": "1.19",
  "gitCommit": "c196fbefa329c9f064ae8c2e3101b8da03f7d931",
  "buildDate": "2022-09-27T00:19:32+00:00",
  "goVersion": "go1.19.1",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**Comment by jsafrane** [comment]
Removed `VERSION` env. var - CI sets it to go version, not to CSI driver version
+ cleaned up the last carry patch that removes KUBECONFIG.

**Comment by Phaow** [comment]
Pre verify pass with `* Clusterversion: 4.12.0-0.ci.test-2022-09-27-101247-ci-ln-qy5rtjk-latest * Platform: AWS * NetWorking: OVNKubernetes *`
 All the **[regression automation test](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/ginkgo-test/112686/console)** passed and the new feature about `Tags` usage manual test passed.
```
60 pass, 57 skip (1h1m16s)
```
The driverVersion issue fixed, currently there's an upstream  issue the `v1.11.4` not update the version in Makefile so still `v1.11.3`.
```
$ oc -n openshift-cluster-csi-drivers exec -c csi-driver deploy/aws-ebs-csi-driver-controller -- /bin/aws-ebs-csi-driver -version | jq .
{
  "driverVersion": "v1.11.3",
  "gitCommit": "3b8232ac94da43dba9a73ac71927c65a9434605a",
  "buildDate": "2022-09-27T10:11:20+00:00",
  "goVersion": "go1.19.1",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**Pull request merged**
